'use client';

import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, ChevronLeft, Upload, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

import { C, grad } from '@/components/tokens';
import { GradBtn } from '@/components/ui/grad-btn';
import { Tooltip } from '@/components/ui/tooltip';
import { api } from '@/lib/api';
import { isSupportedImageBytes } from '@/lib/image-validation';

interface CatalogueImageOption {
  jobId: string;
  catalogueId: string;
}

interface SampleVideoOption {
  id: string;
  title: string;
  thumbnailUrl: string;
  previewVideoUrl: string;
}

type CatalogueResponse = Array<{
  catalogueId: string;
  jobs: Array<{ id: string; status: string }>;
}>;

// The two ways a video can be sourced: an existing completed AI Vastra job
// (from the catalogues grid), or a fresh upload of any image the user owns —
// not required to have been generated by AI Vastra at all.
type ImageSource =
  | { kind: 'existing'; jobId: string }
  | { kind: 'upload'; r2Key: string; previewUrl: string };

// `/v1/catalogues` only carries one cover thumbnail per catalogue (correct for
// the catalogue grid, which shows one card per catalogue) — a catalogue with
// several completed pose jobs has no per-job thumbnail there. Fetch each job's
// own thumbnail directly, same as the catalogue detail page's ImageCard, so
// every option in this picker shows its own generated image instead of all
// jobs from one catalogue displaying that catalogue's single cover photo.
function JobThumbnail({ jobId, alt }: { jobId: string; alt: string }): React.ReactElement {
  const { data } = useQuery<{ url: string }>({
    queryKey: ['job-thumb', jobId],
    queryFn: () => api.get(`/v1/jobs/${jobId}/thumbnail`),
    staleTime: 55 * 60 * 1000,
  });

  if (!data?.url) {
    return <span style={{ color: C.mid, fontSize: 12 }}>Image unavailable</span>;
  }
  return (
    // eslint-disable-next-line @next/next/no-img-element
    // biome-ignore lint/performance/noImgElement: presigned R2 URL
    <img src={data.url} alt={alt} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
  );
}

// Click-to-browse or drag-and-drop upload, mirroring Studio's garment upload
// (handleGarmentUpload in apps/(app)/studio/page.tsx): magic-byte validation,
// 10MB soft cap, local blob-URL preview before the network round trip. Fixed
// aspect ratio across every state (idle/uploading/filled) so picking a file
// doesn't reflow the layout next to it.
function UploadDropzone({
  onFile,
  onRemove,
  uploading,
  progress,
  error,
  previewUrl,
}: {
  onFile: (file: File) => void;
  onRemove: () => void;
  uploading: boolean;
  progress: number;
  error: string | null;
  previewUrl: string | null;
}): React.ReactElement {
  const [dragOver, setDragOver] = useState(false);

  return (
    <div style={{ flex: '0 1 300px', minWidth: 220 }}>
      {/* A <label> wrapping the file input is natively keyboard-accessible
          (click or Enter/Space on the label activates the input) — same
          pattern as Studio's garment upload zones. No custom onClick/onKeyDown
          needed, unlike a plain <div>. */}
      <label
        onDragOver={(event) => {
          event.preventDefault();
          if (!uploading) setDragOver(true);
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(event) => {
          event.preventDefault();
          setDragOver(false);
          const file = event.dataTransfer.files?.[0];
          if (file && !uploading) onFile(file);
        }}
        style={{
          position: 'relative',
          aspectRatio: '3 / 4',
          overflow: 'hidden',
          border: previewUrl
            ? `1px solid ${C.border}`
            : `2px dashed ${dragOver ? C.pink : C.border}`,
          borderRadius: 12,
          background: previewUrl ? C.lighter : dragOver ? 'rgba(245,92,122,0.04)' : C.lighter,
          cursor: uploading ? 'not-allowed' : 'pointer',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          transition: 'background 150ms ease, border-color 150ms ease',
        }}
      >
        <input
          type="file"
          disabled={uploading}
          accept="image/jpeg,image/png,image/webp"
          style={{ display: 'none' }}
          onChange={(event) => {
            const file = event.target.files?.[0];
            event.target.value = '';
            if (file) onFile(file);
          }}
        />
        {previewUrl ? (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            {/* biome-ignore lint/performance/noImgElement: local blob URL preview */}
            <img
              src={previewUrl}
              alt="Uploaded"
              style={{ width: '100%', height: '100%', objectFit: 'cover' }}
            />
            <button
              type="button"
              aria-label="Remove uploaded image"
              onClick={(event) => {
                event.preventDefault();
                event.stopPropagation();
                onRemove();
              }}
              style={{
                position: 'absolute',
                top: 10,
                right: 10,
                width: 28,
                height: 28,
                borderRadius: '50%',
                background: 'rgba(0,0,0,0.55)',
                border: 'none',
                color: C.white,
                cursor: 'pointer',
                display: 'grid',
                placeItems: 'center',
              }}
            >
              <X size={14} />
            </button>
          </>
        ) : uploading ? (
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: 12,
              padding: 20,
              width: '100%',
              boxSizing: 'border-box',
            }}
          >
            <div
              style={{
                width: 44,
                height: 44,
                borderRadius: '50%',
                border: `1px solid ${C.border}`,
                display: 'grid',
                placeItems: 'center',
                color: C.pink,
              }}
            >
              <Upload size={20} />
            </div>
            <div style={{ fontSize: 13, fontWeight: 600, color: C.text }}>
              Uploading… {progress}%
            </div>
            <div
              style={{
                width: '80%',
                height: 4,
                borderRadius: 2,
                background: C.border,
                overflow: 'hidden',
              }}
            >
              <div
                style={{
                  width: `${progress}%`,
                  height: '100%',
                  background: grad,
                  transition: 'width 150ms ease',
                }}
              />
            </div>
          </div>
        ) : (
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: 14,
              padding: 20,
              textAlign: 'center',
            }}
          >
            <div
              style={{
                width: 56,
                height: 56,
                borderRadius: '50%',
                background: dragOver ? 'rgba(245,92,122,0.12)' : C.card,
                border: `1px solid ${dragOver ? C.pink : C.border}`,
                display: 'grid',
                placeItems: 'center',
                color: dragOver ? C.pink : C.mid,
                transition: 'background 150ms ease, border-color 150ms ease, color 150ms ease',
              }}
            >
              <Upload size={24} />
            </div>
            <div style={{ fontSize: 15, fontWeight: 700, color: C.text }}>
              Click or drag an image here
            </div>
            <div style={{ fontSize: 12, color: C.mid, lineHeight: 1.5 }}>
              JPEG, PNG, or WebP · up to 10MB
            </div>
          </div>
        )}
      </label>
      {previewUrl && !error && (
        <p style={{ margin: '8px 0 0', color: C.mid, fontSize: 12 }}>
          Looks good — click the × to choose a different photo.
        </p>
      )}
      {error && <p style={{ margin: '8px 0 0', color: '#D63B4C', fontSize: 12 }}>{error}</p>}
    </div>
  );
}

// Fills the space next to the dropzone with guidance instead of empty
// background — the kind of source-photo tips premium photo-upload flows
// (ID verification, e-commerce listings) show rather than leaving the panel
// sparse next to the catalogue-image grid tab.
const UPLOAD_TIPS: Array<{ title: string; body: string }> = [
  {
    title: 'Clear, well-lit photo',
    body: 'Natural or bright indoor light works best — avoid harsh shadows or backlighting.',
  },
  { title: 'Full outfit in frame', body: "Make sure the garment isn't cropped out of the shot." },
  {
    title: 'One person, simple background',
    body: 'Avoid group photos or busy, cluttered backgrounds.',
  },
  {
    title: 'Minimal filters or edits',
    body: 'Unedited or lightly edited photos animate more naturally.',
  },
];

function UploadTips(): React.ReactElement {
  return (
    <div
      style={{
        flex: '1 1 260px',
        display: 'flex',
        flexDirection: 'column',
        border: `1px solid ${C.border}`,
        borderRadius: 12,
        background: C.card,
        padding: '24px 26px',
        boxSizing: 'border-box',
      }}
    >
      <div>
        <div style={{ fontSize: 15, fontWeight: 700, color: C.text }}>For the best results</div>
        <div style={{ fontSize: 12, color: C.mid, marginTop: 4, lineHeight: 1.5 }}>
          A few pointers that make the animation look its best.
        </div>
      </div>
      {/* Distributes the tip rows through the full remaining height instead of
          leaving them glued to the top with dead space below — the card's
          height already matches the dropzone via flex stretch, so this makes
          the two panels feel like one deliberate layout. */}
      <div
        style={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-evenly',
          gap: 20,
          marginTop: 8,
        }}
      >
        {UPLOAD_TIPS.map((tip) => (
          <div key={tip.title} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
            <span
              style={{
                flexShrink: 0,
                width: 22,
                height: 22,
                borderRadius: '50%',
                background: 'rgba(245,92,122,0.12)',
                color: C.pink,
                display: 'grid',
                placeItems: 'center',
                marginTop: 1,
              }}
            >
              <Check size={13} />
            </span>
            <div>
              <div style={{ fontSize: 14, fontWeight: 600, color: C.text, lineHeight: 1.4 }}>
                {tip.title}
              </div>
              <div style={{ fontSize: 13, color: C.mid, lineHeight: 1.55, marginTop: 3 }}>
                {tip.body}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export function CatalogVideoWizard({
  onClose,
  onCreated,
}: {
  onClose: () => void;
  onCreated: () => void;
}): React.ReactElement {
  const qc = useQueryClient();
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [sourceTab, setSourceTab] = useState<'existing' | 'upload'>('existing');
  const [source, setSource] = useState<ImageSource | null>(null);
  const [sampleVideoId, setSampleVideoId] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const uploadAbortRef = useRef<AbortController | null>(null);

  // Revoke the previous upload's blob URL whenever `source` changes away from
  // it (a new upload, switching to an existing-image selection, or unmount) —
  // never the currently active one.
  useEffect(() => {
    return () => {
      if (source?.kind === 'upload') URL.revokeObjectURL(source.previewUrl);
    };
  }, [source]);

  const { data: catalogues, isLoading: cataloguesLoading } = useQuery<CatalogueResponse>({
    queryKey: ['catalogues'],
    queryFn: () => api.get('/v1/catalogues'),
  });

  const { data: sampleVideos, isLoading: sampleVideosLoading } = useQuery<{
    creditCost: number;
    items: SampleVideoOption[];
  }>({
    queryKey: ['sample-videos'],
    queryFn: () => api.get('/v1/models/sample-videos'),
    enabled: step >= 2,
  });

  const { data: creditsData } = useQuery<{ balance: number }>({
    queryKey: ['credits'],
    queryFn: () => api.get('/v1/credits'),
    enabled: step >= 2,
  });

  const creditCost = sampleVideos?.creditCost;
  const balance = creditsData?.balance;
  const insufficientCredits =
    typeof creditCost === 'number' && typeof balance === 'number' && balance < creditCost;

  const imageOptions: CatalogueImageOption[] = (catalogues ?? []).flatMap((catalogue) =>
    catalogue.jobs
      .filter((job) => job.status === 'COMPLETED')
      .map((job) => ({
        jobId: job.id,
        catalogueId: catalogue.catalogueId,
      })),
  );
  const selectedSample = sampleVideos?.items.find((option) => option.id === sampleVideoId);

  async function handleUpload(file: File) {
    if (uploading) return;
    if (file.size > 10 * 1024 * 1024) {
      setUploadError('File exceeds 10 MB. Please choose a smaller image.');
      return;
    }
    if (!(await isSupportedImageBytes(file))) {
      setUploadError('Unsupported file type. Please upload a JPEG, PNG, or WebP image.');
      return;
    }
    setUploadError(null);
    setUploading(true);
    setUploadProgress(0);
    const abort = new AbortController();
    uploadAbortRef.current = abort;
    const previewUrl = URL.createObjectURL(file);
    try {
      const { uploadUrl, r2Key } = await api.post<{
        uploadUrl: string;
        r2Key: string;
        expiresIn: number;
      }>('/v1/uploads/presign', { contentType: file.type, contentLength: file.size });
      await api.uploadToR2WithProgress(uploadUrl, file, setUploadProgress, abort.signal);
      setSource({ kind: 'upload', r2Key, previewUrl });
    } catch (e) {
      URL.revokeObjectURL(previewUrl);
      if (e instanceof DOMException && e.name === 'AbortError') return;
      const msg = e instanceof Error ? e.message : '';
      setUploadError(
        msg.includes('403')
          ? 'Upload session expired. Please re-upload your image and try again.'
          : `Upload failed: ${msg}`,
      );
    } finally {
      setUploading(false);
    }
  }

  function handleClose() {
    if (submitting) return;
    uploadAbortRef.current?.abort();
    onClose();
  }

  const handleSubmit = async () => {
    if (!source || !sampleVideoId || insufficientCredits) return;
    setSubmitting(true);
    setError(null);
    try {
      await api.post('/v1/jobs/catalog-video', {
        ...(source.kind === 'existing'
          ? { sourceJobId: source.jobId }
          : { sourceImageKey: source.r2Key }),
        sampleVideoId,
      });
      await qc.invalidateQueries({ queryKey: ['catalog-videos'] });
      onCreated();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to start video generation');
    } finally {
      setSubmitting(false);
    }
  };

  const nextDisabled =
    (step === 1 && !source) || (step === 2 && !sampleVideoId) || submitting || uploading;

  return (
    <>
      <style>{`
        .wizard-backdrop {
          position: fixed;
          inset: 0;
          z-index: 1000;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 20px;
          background: rgba(8, 12, 24, 0.62);
        }

        .wizard-dialog {
          width: min(960px, calc(100vw - 40px));
          height: min(800px, calc(100vh - 40px));
          overflow: hidden;
          border: 1px solid ${C.border};
          border-radius: 8px;
          background: ${C.card};
          box-shadow: 0 20px 56px rgba(0, 0, 0, 0.32);
          display: flex;
          flex-direction: column;
        }

        .wizard-step1-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
          gap: 12px;
        }

        .wizard-step2-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
          gap: 16px;
        }

        .wizard-step3-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 16px;
        }

        @media (max-width: 639px) {
          .wizard-backdrop {
            padding: 10px;
          }
          .wizard-dialog {
            width: calc(100vw - 20px);
            height: calc(100vh - 20px);
          }
          .wizard-step1-grid {
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
          }
          .wizard-step2-grid {
            grid-template-columns: repeat(2, 1fr);
            gap: 10px;
          }
          .wizard-step3-grid {
            grid-template-columns: 1fr;
            gap: 12px;
          }
        }
      `}</style>
      {/* biome-ignore lint/a11y/noStaticElementInteractions: modal backdrop; click outside dismisses */}
      <div
        role="presentation"
        className="wizard-backdrop"
        onMouseDown={(event) => {
          if (event.target === event.currentTarget) handleClose();
        }}
      >
        <section
          role="dialog"
          aria-modal="true"
          aria-labelledby="catalog-video-wizard-title"
          className="wizard-dialog"
        >
          <header
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: 16,
              padding: '18px 20px',
              borderBottom: `1px solid ${C.border}`,
            }}
          >
            <div>
              <h2
                id="catalog-video-wizard-title"
                style={{ margin: 0, color: C.text, fontSize: 18 }}
              >
                New Catalog Video
              </h2>
              {/* biome-ignore lint/a11y/useSemanticElements: decorative step indicator, not a form control group — <fieldset> would misrepresent it */}
              <div
                role="group"
                style={{ display: 'flex', gap: 6, marginTop: 10 }}
                aria-label={`Step ${step} of 3`}
              >
                {[1, 2, 3].map((item) => (
                  <span
                    key={item}
                    style={{
                      display: 'block',
                      width: 42,
                      height: 3,
                      background: item <= step ? C.pink : C.border,
                    }}
                  />
                ))}
              </div>
            </div>
            <button
              type="button"
              aria-label="Close"
              disabled={submitting}
              onClick={handleClose}
              style={{
                width: 32,
                height: 32,
                border: `1px solid ${C.border}`,
                borderRadius: 6,
                background: 'transparent',
                color: C.mid,
                display: 'grid',
                placeItems: 'center',
                cursor: submitting ? 'not-allowed' : 'pointer',
              }}
            >
              <X size={16} />
            </button>
          </header>

          <div style={{ padding: 20, overflowY: 'auto', flex: 1, minHeight: 0 }}>
            {step === 1 && (
              <>
                <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
                  {(['existing', 'upload'] as const).map((tab) => (
                    <button
                      key={tab}
                      type="button"
                      aria-pressed={sourceTab === tab}
                      onClick={() => setSourceTab(tab)}
                      style={{
                        padding: '8px 16px',
                        borderRadius: 999,
                        border: `1px solid ${sourceTab === tab ? C.pink : C.border}`,
                        background: sourceTab === tab ? 'rgba(245,92,122,0.08)' : 'transparent',
                        color: sourceTab === tab ? C.pink : C.mid,
                        fontSize: 13,
                        fontWeight: 600,
                        cursor: 'pointer',
                      }}
                    >
                      {tab === 'existing' ? 'My Catalogue Images' : 'Upload New'}
                    </button>
                  ))}
                </div>

                {sourceTab === 'existing' ? (
                  <>
                    <p style={{ margin: '0 0 16px', color: C.mid, fontSize: 13 }}>
                      Choose a completed catalogue image.
                    </p>
                    {cataloguesLoading ? (
                      <p style={{ color: C.mid, fontSize: 13 }}>Loading images...</p>
                    ) : imageOptions.length === 0 ? (
                      <p style={{ color: C.mid, fontSize: 13 }}>
                        No completed catalogue images are available.
                      </p>
                    ) : (
                      <div className="wizard-step1-grid">
                        {imageOptions.map((option) => {
                          const selected =
                            source?.kind === 'existing' && source.jobId === option.jobId;
                          return (
                            <button
                              key={option.jobId}
                              type="button"
                              aria-pressed={selected}
                              onClick={() => setSource({ kind: 'existing', jobId: option.jobId })}
                              style={{
                                position: 'relative',
                                aspectRatio: '3 / 4',
                                overflow: 'hidden',
                                border: selected ? `2px solid ${C.pink}` : `1px solid ${C.border}`,
                                borderRadius: 6,
                                padding: 0,
                                background: C.lighter,
                                cursor: 'pointer',
                              }}
                            >
                              <JobThumbnail jobId={option.jobId} alt="" />
                              {selected && (
                                <span
                                  style={{
                                    position: 'absolute',
                                    top: 8,
                                    right: 8,
                                    width: 22,
                                    height: 22,
                                    borderRadius: 999,
                                    background: C.pink,
                                    color: C.white,
                                    display: 'grid',
                                    placeItems: 'center',
                                  }}
                                >
                                  <Check size={14} />
                                </span>
                              )}
                            </button>
                          );
                        })}
                      </div>
                    )}
                  </>
                ) : (
                  <>
                    <p style={{ margin: '0 0 16px', color: C.mid, fontSize: 13 }}>
                      Upload any photo you own — it doesn't need to be an AI Vastra generation.
                    </p>
                    <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
                      <UploadDropzone
                        onFile={handleUpload}
                        onRemove={() => setSource(null)}
                        uploading={uploading}
                        progress={uploadProgress}
                        error={uploadError}
                        previewUrl={source?.kind === 'upload' ? source.previewUrl : null}
                      />
                      <UploadTips />
                    </div>
                  </>
                )}
              </>
            )}

            {step === 2 && (
              <>
                <p style={{ margin: '0 0 8px', color: C.mid, fontSize: 13 }}>
                  Choose the motion template for your video.
                </p>
                {typeof creditCost === 'number' && (
                  <p
                    style={{
                      margin: '0 0 16px',
                      fontSize: 12,
                      fontWeight: 600,
                      color: insufficientCredits ? '#D63B4C' : C.mid,
                    }}
                  >
                    {creditCost} credits required
                    {typeof balance === 'number' ? ` — you have ${balance} credits` : ''}
                    {insufficientCredits ? '. Top up to generate a video.' : ''}
                  </p>
                )}
                {sampleVideosLoading ? (
                  <p style={{ color: C.mid, fontSize: 13 }}>Loading motion templates...</p>
                ) : (sampleVideos?.items.length ?? 0) === 0 ? (
                  <p style={{ color: C.mid, fontSize: 13 }}>No video templates are available.</p>
                ) : (
                  <div className="wizard-step2-grid">
                    {(sampleVideos?.items ?? []).map((option) => {
                      const selected = option.id === sampleVideoId;
                      return (
                        <button
                          key={option.id}
                          type="button"
                          aria-pressed={selected}
                          onClick={() => setSampleVideoId(option.id)}
                          style={{
                            position: 'relative',
                            padding: 0,
                            textAlign: 'left',
                            overflow: 'hidden',
                            border: selected ? `2px solid ${C.pink}` : `1px solid ${C.border}`,
                            borderRadius: 8,
                            background: C.card,
                            cursor: 'pointer',
                          }}
                        >
                          <div
                            style={{
                              position: 'relative',
                              aspectRatio: '9 / 16',
                              background: C.lighter,
                            }}
                          >
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            {/* biome-ignore lint/performance/noImgElement: animated GIF preview, presigned R2 URL */}
                            <img
                              src={option.thumbnailUrl}
                              alt={option.title}
                              style={{
                                width: '100%',
                                height: '100%',
                                objectFit: 'cover',
                                display: 'block',
                              }}
                            />
                            {selected && (
                              <span
                                style={{
                                  position: 'absolute',
                                  top: 10,
                                  right: 10,
                                  width: 22,
                                  height: 22,
                                  borderRadius: 999,
                                  background: C.pink,
                                  color: C.white,
                                  display: 'grid',
                                  placeItems: 'center',
                                }}
                              >
                                <Check size={14} />
                              </span>
                            )}
                          </div>
                          <span
                            style={{
                              display: 'block',
                              padding: '10px 12px',
                              overflow: 'hidden',
                              textOverflow: 'ellipsis',
                              whiteSpace: 'nowrap',
                              color: C.text,
                              fontSize: 13,
                              fontWeight: 600,
                            }}
                          >
                            {option.title}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                )}
              </>
            )}

            {step === 3 && (
              <div className="wizard-step3-grid">
                <div
                  style={{ border: `1px solid ${C.border}`, borderRadius: 6, overflow: 'hidden' }}
                >
                  <div style={{ aspectRatio: '3 / 4', background: C.lighter }}>
                    {source?.kind === 'existing' && (
                      <JobThumbnail jobId={source.jobId} alt="Selected catalogue" />
                    )}
                    {source?.kind === 'upload' && (
                      // eslint-disable-next-line @next/next/no-img-element
                      // biome-ignore lint/performance/noImgElement: local blob URL preview
                      <img
                        src={source.previewUrl}
                        alt="Selected upload"
                        style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                      />
                    )}
                  </div>
                  <div style={{ padding: 10, color: C.mid, fontSize: 12 }}>
                    {source?.kind === 'upload' ? 'Uploaded image' : 'Catalogue image'}
                  </div>
                </div>
                <div
                  style={{ border: `1px solid ${C.border}`, borderRadius: 6, overflow: 'hidden' }}
                >
                  <div style={{ aspectRatio: '3 / 4', background: C.lighter }}>
                    {selectedSample && (
                      <video
                        src={selectedSample.previewVideoUrl}
                        poster={selectedSample.thumbnailUrl}
                        muted
                        controls
                        style={{
                          width: '100%',
                          height: '100%',
                          objectFit: 'cover',
                          display: 'block',
                        }}
                      />
                    )}
                  </div>
                  <div style={{ padding: 10, color: C.mid, fontSize: 12 }}>
                    {selectedSample?.title ?? 'Motion template'}
                  </div>
                </div>
                {insufficientCredits && (
                  <p style={{ gridColumn: '1 / -1', margin: 0, color: '#D63B4C', fontSize: 13 }}>
                    This video costs {creditCost} credits and you have {balance} credits. Top up to
                    generate this video.
                  </p>
                )}
                {error && (
                  <p style={{ gridColumn: '1 / -1', margin: 0, color: '#D63B4C', fontSize: 13 }}>
                    {error}
                  </p>
                )}
              </div>
            )}
          </div>

          <footer
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: 12,
              padding: '16px 20px',
              borderTop: `1px solid ${C.border}`,
            }}
          >
            {step > 1 ? (
              <button
                type="button"
                disabled={submitting}
                onClick={() => setStep((current) => (current - 1) as 1 | 2 | 3)}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 6,
                  border: 'none',
                  background: 'transparent',
                  color: C.mid,
                  padding: 8,
                  fontSize: 13,
                  cursor: submitting ? 'not-allowed' : 'pointer',
                }}
              >
                <ChevronLeft size={16} />
                Back
              </button>
            ) : (
              <span />
            )}
            {step < 3 ? (
              <GradBtn
                disabled={nextDisabled}
                onClick={() => setStep((current) => (current + 1) as 1 | 2 | 3)}
              >
                Next
              </GradBtn>
            ) : (
              <Tooltip
                tip={
                  insufficientCredits
                    ? `You need ${creditCost} credits and have ${balance}. Top up to continue.`
                    : undefined
                }
              >
                <GradBtn disabled={submitting || insufficientCredits} onClick={handleSubmit}>
                  {submitting ? 'Starting...' : 'Generate video'}
                </GradBtn>
              </Tooltip>
            )}
          </footer>
        </section>
      </div>
    </>
  );
}
