import { randomUUID } from 'node:crypto';
import { schema } from '@tryme/db';
import { createLogger } from '@tryme/logger';
import { eq } from 'drizzle-orm';
import { Redis } from 'ioredis';
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from 'vitest';

import { runVideoConsumer } from '../../src/stream/video-consumer.js';
import { getWorkers } from '../../src/worker/registry.js';
import { setupTestEnv, type TestEnv } from '../helpers/containers.js';

const GROUP = 'dispatcher-cg';

/**
 * Regression coverage for the GPU-capacity coupling bug: catalog-video jobs are
 * generated by PixVerse over HTTP and need no ComfyUI worker, but they used to ride
 * the shared jobs:* streams whose consumer caps in-flight work at the worker-registry
 * size. With zero registered workers that cap is 0, so the message was never even read
 * and the job sat QUEUED until the sweeper refunded it.
 */
describe('video lane (jobs:video)', () => {
  let env: TestEnv;
  let redis: Redis;
  let pub: Redis;
  const createdStreams: string[] = [];

  beforeAll(async () => {
    env = await setupTestEnv();
    redis = new Redis('redis://127.0.0.1:6379');
    pub = new Redis('redis://127.0.0.1:6379');
    // worker:registry is a single global key on the shared dev Redis, and singleFork
    // runs test files sequentially in one process — so a file that crashed before its
    // afterAll can leave a worker behind. Clear it so the zero-workers precondition
    // below actually means "no GPU capacity".
    await redis.del('worker:registry');
  }, 60_000);

  afterAll(async () => {
    for (const s of createdStreams) await redis.del(s);
    redis.disconnect();
    pub.disconnect();
    await env.cleanup();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  /**
   * One stream per test. Stopping a loop only clears its `running` flag — it can still
   * be parked inside a 5s BLOCK read and will process whatever that read returns, so a
   * shared stream lets a finished test's consumer steal the next test's message.
   */
  function newStream(name: string): string {
    const s = `jobs:video-test-${name}-${randomUUID().slice(0, 8)}`;
    createdStreams.push(s);
    return s;
  }

  function cfg() {
    return {
      db: env.db,
      redis,
      pub,
      storage: env.storage,
      s3: env.s3,
      r2Bucket: env.r2Bucket,
      log: createLogger('test'),
    };
  }

  async function seedVideoJob() {
    const [user] = await env.db
      .insert(schema.users)
      .values({ email: `vlane-${randomUUID()}@test.com`, passwordHash: 'x', tier: 'free' })
      .returning();
    await env.db.insert(schema.userCredits).values({ userId: user?.id, balance: 0 });

    const [sourceJob] = await env.db
      .insert(schema.jobs)
      .values({ userId: user?.id, status: 'COMPLETED', creditsCharged: 5 })
      .returning();
    await env.db.insert(schema.jobInputs).values({ jobId: sourceJob?.id });
    await env.db.insert(schema.jobOutputs).values({
      jobId: sourceJob?.id,
      resultKey: `outputs/${sourceJob?.id}/result.png`,
    });

    const [job] = await env.db
      .insert(schema.jobs)
      .values({
        userId: user?.id,
        status: 'QUEUED',
        creditsCharged: 20,
        source: 'catalog_video',
        queueStream: 'video',
      })
      .returning();
    await env.db.insert(schema.jobInputs).values({
      jobId: job?.id,
      params: {
        kind: 'video',
        sourceJobId: sourceJob?.id,
        sourceImageKey: `outputs/${sourceJob?.id}/result.png`,
        sampleVideoId: randomUUID(),
        prompt: 'model turning slowly',
      },
    });

    return { jobId: job?.id as string, userId: user?.id as string };
  }

  /** Mocks the PixVerse happy path. `onGenerate` gates task creation. */
  function mockPixverseOk(onGenerate?: () => Promise<void>) {
    const spy = vi.spyOn(globalThis, 'fetch');
    spy.mockImplementation(async (input: RequestInfo | URL) => {
      const url = input.toString();
      // createVideoTask uploads the source image before creating the task.
      if (url.includes('/image/upload')) {
        return new Response(JSON.stringify({ ErrCode: 0, Resp: { img_id: 123 } }), { status: 200 });
      }
      if (url.includes('/video/img/generate')) {
        if (onGenerate) await onGenerate();
        return new Response(JSON.stringify({ ErrCode: 0, Resp: { video_id: 456 } }), {
          status: 200,
        });
      }
      if (url.includes('/video/result/')) {
        return new Response(
          JSON.stringify({
            ErrCode: 0,
            Resp: { status: 1, url: 'https://pixverse.example/video.mp4' },
          }),
          { status: 200 },
        );
      }
      if (url === 'https://pixverse.example/video.mp4') {
        return new Response(Buffer.from('fake-mp4-bytes'), { status: 200 });
      }
      throw new Error(`unexpected fetch: ${url}`);
    });
    return spy;
  }

  async function statusOf(jobId: string): Promise<string> {
    const [row] = await env.db.select().from(schema.jobs).where(eq(schema.jobs.id, jobId));
    return row?.status as string;
  }

  /** Polls until `want` or a terminal status is reached; returns the last seen status. */
  async function waitForStatus(jobId: string, want: string, timeoutMs = 20_000): Promise<string> {
    const deadline = Date.now() + timeoutMs;
    let last = '';
    while (Date.now() < deadline) {
      last = await statusOf(jobId);
      if (last === want) return last;
      if (last === 'FAILED' || last === 'CANCELLED') return last;
      await new Promise((r) => setTimeout(r, 100));
    }
    return last;
  }

  it('processes a video job to COMPLETED with zero GPU workers registered', async () => {
    // The whole point of the lane. If the registry were non-empty the assertion below
    // would still hold but would no longer prove decoupling — so require it.
    expect((await getWorkers(redis)).size).toBe(0);

    const stream = newStream('zero-workers');
    const { jobId, userId } = await seedVideoJob();
    mockPixverseOk();

    const stop = await runVideoConsumer(redis, cfg(), createLogger('test'), {
      concurrency: 2,
      stream,
    });
    try {
      await redis.xadd(stream, '*', 'jobId', jobId, 'userId', userId);
      expect(await waitForStatus(jobId, 'COMPLETED')).toBe('COMPLETED');
    } finally {
      stop();
    }

    // Group is created under the shared dispatcher group name.
    const groups = (await redis.xinfo('GROUPS', stream)) as unknown[][];
    expect(groups.map((g) => g[1])).toContain(GROUP);
  });

  it('never runs more jobs at once than the configured concurrency', async () => {
    const stream = newStream('concurrency');
    const jobs = await Promise.all([seedVideoJob(), seedVideoJob(), seedVideoJob()]);

    // Hold every job inside createVideoTask until released, so "started" means
    // "currently occupying a slot".
    let release!: () => void;
    const gate = new Promise<void>((resolve) => {
      release = resolve;
    });
    let started = 0;
    mockPixverseOk(async () => {
      started++;
      await gate;
    });

    const stop = await runVideoConsumer(redis, cfg(), createLogger('test'), {
      concurrency: 1,
      stream,
    });
    try {
      for (const j of jobs) await redis.xadd(stream, '*', 'jobId', j.jobId, 'userId', j.userId);

      // Ample time for the loop to over-read if the cap were not enforced.
      await new Promise((r) => setTimeout(r, 2_000));
      expect(started).toBe(1);

      release();
      for (const j of jobs) expect(await waitForStatus(j.jobId, 'COMPLETED')).toBe('COMPLETED');
    } finally {
      release();
      stop();
    }
  });

  it('re-enqueues a failed job onto the video lane, not a GPU stream', async () => {
    const stream = newStream('retry');
    const { jobId, userId } = await seedVideoJob();

    vi.spyOn(globalThis, 'fetch').mockImplementation(async (input: RequestInfo | URL) => {
      const url = input.toString();
      if (url.includes('/image/upload')) {
        return new Response(JSON.stringify({ ErrCode: 0, Resp: { img_id: 123 } }), { status: 200 });
      }
      if (url.includes('/video/img/generate')) {
        return new Response(JSON.stringify({ ErrCode: 0, Resp: { video_id: 456 } }), {
          status: 200,
        });
      }
      if (url.includes('/video/result/')) {
        return new Response(
          JSON.stringify({ ErrCode: 0, ErrMsg: 'content policy violation', Resp: { status: 7 } }),
          { status: 200 },
        );
      }
      throw new Error(`unexpected fetch: ${url}`);
    });

    const normalBefore = await redis.xlen('jobs:normal');

    const stop = await runVideoConsumer(redis, cfg(), createLogger('test'), {
      concurrency: 1,
      stream,
    });
    try {
      await redis.xadd(stream, '*', 'jobId', jobId, 'userId', userId);

      // Attempt 1 fails and handleFailure re-XADDs; the loop picks the retry up and
      // attempt 2 hits MAX_ATTEMPTS, terminating with a refund.
      expect(await waitForStatus(jobId, 'FAILED')).toBe('FAILED');

      // 1 for our enqueue + 1 for the retry — both on the video stream.
      expect(await redis.xlen(stream)).toBe(2);
      expect(await redis.xlen('jobs:normal')).toBe(normalBefore);
    } finally {
      stop();
    }
  });

  it('delivers messages enqueued before the consumer group existed', async () => {
    // Guards the '0' (not '$') group start-id: the API may deploy and enqueue before
    // the dispatcher boots, and those jobs must not be silently skipped.
    const stream = newStream('pre-existing');
    const { jobId, userId } = await seedVideoJob();
    mockPixverseOk();

    await redis.xadd(stream, '*', 'jobId', jobId, 'userId', userId);
    expect(await redis.xlen(stream)).toBe(1);

    const stop = await runVideoConsumer(redis, cfg(), createLogger('test'), {
      concurrency: 1,
      stream,
    });
    try {
      expect(await waitForStatus(jobId, 'COMPLETED')).toBe('COMPLETED');
    } finally {
      stop();
    }
  });
});
