import { hostname } from 'node:os';
import type { Logger } from '@tryme/logger';
import type { Redis } from 'ioredis';
import type { ProcessorConfig } from '../job/processor.js';
import { DISPATCHER_GROUP, parseMessage, runStreamLoop, type XReadGroupResult } from './loop.js';

export const VIDEO_STREAM = 'jobs:video';

// Distinct from the GPU consumer's plain hostname so the two lanes are separable
// in `XINFO CONSUMERS jobs:video dispatcher-cg`.
const CONSUMER = `${hostname()}-video`;
const BLOCK_MS = 5_000;

async function ensureVideoGroup(redis: Redis, stream: string, log: Logger): Promise<void> {
  try {
    // '0' not '$': jobs:video is a new stream with no legacy backlog to replay, so
    // starting at 0 costs nothing — and it means a job the API enqueued between its
    // own deploy and this dispatcher's boot is still delivered. With '$', MKSTREAM
    // would find a non-empty stream and silently skip everything in that window.
    await redis.xgroup('CREATE', stream, DISPATCHER_GROUP, '0', 'MKSTREAM');
    log.info({ stream }, 'video consumer group created');
  } catch (err: unknown) {
    // BUSYGROUP = group already exists, safe to ignore
    if (!(err instanceof Error) || !err.message.includes('BUSYGROUP')) throw err;
  }
}

export interface VideoConsumerOptions {
  /** In-flight cap for this lane. From env, deliberately NOT the worker registry. */
  concurrency: number;
  /** Test-only stream override; production always uses VIDEO_STREAM. */
  stream?: string;
}

/**
 * Video lane consumer.
 *
 * Catalog-video jobs are generated by PixVerse over HTTP and never touch ComfyUI or
 * claim a GPU worker, so they must not be gated by GPU capacity. On the shared
 * jobs:priority/normal/low streams they were: the GPU consumer caps in-flight jobs
 * to the worker-registry size, which blocks reads entirely when no worker is
 * registered — video jobs then sat QUEUED until the sweeper refunded them.
 *
 * This lane reads jobs:video with a fixed env-driven cap instead.
 */
export async function runVideoConsumer(
  redis: Redis,
  cfg: ProcessorConfig,
  log: Logger,
  opts: VideoConsumerOptions,
): Promise<() => void> {
  const stream = opts.stream ?? VIDEO_STREAM;

  // Dedicated connection: XREADGROUP ... BLOCK parks the connection server-side, and
  // the shared `main` connection already carries the GPU consumer's 2s block on
  // jobs:low, the webhooks consumer's 2s block, every XACK, the worker-registry
  // HGETALL and recovery's XPENDING/XCLAIM. A third blocking loop on it would add
  // head-of-line latency to all of those.
  const readConn = redis.duplicate();

  await ensureVideoGroup(readConn, stream, log);

  const stop = runStreamLoop(cfg, log, {
    name: 'video',
    read: async () =>
      parseMessage(
        stream,
        (await readConn.xreadgroup(
          'GROUP',
          DISPATCHER_GROUP,
          CONSUMER,
          'COUNT',
          '1',
          'BLOCK',
          String(BLOCK_MS),
          'STREAMS',
          stream,
          '>',
        )) as XReadGroupResult,
      ),
    getConcurrency: async () => opts.concurrency,
  });

  log.info({ stream, concurrency: opts.concurrency }, 'video consumer started');

  return () => {
    stop();
    void readConn.quit().catch(() => {});
  };
}
